spring:
  config:
    import: classpath:extension.yml
  ai:
    mcp:
      server:
        name: mcp-mysql-server
        version: 1.0.0
        stdio: true
server:
  port: 9433
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /Users/xin.y/Downloads/mcpLog/mcp.log
