spring:
  config:
    import: classpath:extension.yml
  ai:
    mcp:
      server:
        name: mcp-mysql-server
        version: 1.0.0
        stdio: true
  application:
    name: mcp-mysql-server
  main:
    banner-mode: off
server:
  port: 9433
logging:
  file:
    name: logs/mcp-server.log
  level:
    root: OFF
  pattern:
    console: ""
